# Generated by Django 2.2.4 on 2019-09-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='abstract',
        ),
    ]
